name: Build on Ubuntu
run-name: building & testing on Ubuntu
on:
  push:
    branches:
      - 'build-ubuntu/**'
      - 'build/**'
jobs:
  Build-on-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Branch [ ${{ github.ref }} ]  Repository [ ${{ github.repository }} ]"
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: make kpathsea
        shell: bash
        run: |
          mkdir -p ./source/Work/texk/kpathsea
          cd ${{ github.workspace }}/source/Work/texk/kpathsea
          ../../../texk/kpathsea/configure
          make
          make check || cat tests/kpsesafe.log

      - name: upmendex
        shell: bash
        run: |
          mkdir -p ./source/Work/texk/upmendex
          cd ./source/Work/texk/upmendex
          ../../../texk/upmendex/configure \
            --with-system-icu
          make
          ./upmendex --help
          make check

      - name: upmendex samples
        shell: bash
        run: |
          cd ./doc/samples
          make -e all
          make compare
          cd ./alphabet
          make -e alphabet
          make compare
          cd ../option
          make -e all
          make compare
        env:
          TEXMFCNF: "${{ github.workspace }}/source/texk/kpathsea"
          UPMENDEX: "${{ github.workspace }}/source/Work/texk/upmendex/upmendex"

      - run: echo "⛄ This job's status is ${{ job.status }}."
